// Code generated by mockery v2.17.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	internalgrpc "github.com/alexilallas/grpcproxy/internal/grpc"

	mock "github.com/stretchr/testify/mock"
)

// TaskManagerClient is an autogenerated mock type for the TaskManagerClient type
type TaskManagerClient struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, in, opts
func (_m *TaskManagerClient) CreateTask(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*internalgrpc.Task, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *internalgrpc.Task
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *internalgrpc.Task); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgrpc.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: ctx, in, opts
func (_m *TaskManagerClient) GetTask(ctx context.Context, in *internalgrpc.Task, opts ...grpc.CallOption) (*internalgrpc.Task, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *internalgrpc.Task
	if rf, ok := ret.Get(0).(func(context.Context, *internalgrpc.Task, ...grpc.CallOption) *internalgrpc.Task); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgrpc.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *internalgrpc.Task, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTaskManagerClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewTaskManagerClient creates a new instance of TaskManagerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTaskManagerClient(t mockConstructorTestingTNewTaskManagerClient) *TaskManagerClient {
	mock := &TaskManagerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
