// Code generated by mockery v2.17.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTaskManagerServer is an autogenerated mock type for the UnsafeTaskManagerServer type
type UnsafeTaskManagerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTaskManagerServer provides a mock function with given fields:
func (_m *UnsafeTaskManagerServer) mustEmbedUnimplementedTaskManagerServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeTaskManagerServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeTaskManagerServer creates a new instance of UnsafeTaskManagerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeTaskManagerServer(t mockConstructorTestingTNewUnsafeTaskManagerServer) *UnsafeTaskManagerServer {
	mock := &UnsafeTaskManagerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
